import {test,expect} from '@playwright/test';
test('authored overlay pauses Story, updates persistent preferences and rejects stale page actions',async({page})=>{
  await page.setViewportSize({width:1280,height:720});
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto('http://127.0.0.1:4206/?test=1&backend=webgl2',{waitUntil:'domcontentloaded'}).catch(e=>{if(!e.message.includes('interrupted'))throw e;});
  await page.waitForFunction(()=>window.__nir?.state().ready&&!window.__nir.state().loading);
  await page.keyboard.press('Enter');
  await page.waitForFunction(()=>window.__nir.state().dialogue&&!window.__nir.state().loading);
  await page.keyboard.press('Escape');
  await page.waitForFunction(()=>window.__nir.state().screen==='Menu'&&!window.__nir.state().loading);
  const speed=page.getByRole('button',{name:'Increase text_speed',exact:true});
  const stale=JSON.parse(await speed.getAttribute('data-action'));
  const before=await page.evaluate(()=>({tick:window.__nir.state().tick_us,interaction:window.__nir.state().interaction,prefs:{text_speed:1,bgm_volume:1,...window.__nir.state().preferences}}));
  await speed.focus();await page.keyboard.press('Enter');
  await expect.poll(()=>page.evaluate(()=>window.__nir.state().preferences.text_speed)).toBe(before.prefs.text_speed+.25);
  await expect(speed).toBeFocused();
  await page.evaluate(a=>window.__nir.action(a),stale);
  expect(await page.evaluate(()=>window.__nir.state().preferences.text_speed)).toBe(before.prefs.text_speed+.25);
  await page.mouse.click(450,310);
  await expect.poll(()=>page.evaluate(()=>window.__nir.state().preferences.bgm_volume)).toBe(Math.min(1,before.prefs.bgm_volume+.25));
  expect(await page.evaluate(()=>window.__nir.state().tick_us)).toBe(before.tick);
  expect(await page.evaluate(()=>window.__nir.state().interaction)).toBe(before.interaction);
  await page.mouse.click(450,535);
  await page.waitForFunction(()=>window.__nir.state().screen==='Story'&&!window.__nir.state().loading);
  expect(await page.evaluate(()=>window.__nir.state().interaction)).toBe(before.interaction);
  await page.keyboard.press('Escape');
  await page.waitForFunction(()=>window.__nir.state().screen==='Menu'&&!window.__nir.state().loading);
  const fresh=JSON.parse(await speed.getAttribute('data-action'));
  expect(fresh.instance).not.toBe(stale.instance);
  await page.evaluate(a=>window.__nir.action(a),stale);
  expect(await page.evaluate(()=>window.__nir.state().preferences.text_speed)).toBe(before.prefs.text_speed+.25);
  await page.reload({waitUntil:'domcontentloaded'});
  await page.waitForFunction(()=>window.__nir?.state().ready&&!window.__nir.state().loading);
  expect(await page.evaluate(()=>window.__nir.state().preferences.text_speed)).toBe(before.prefs.text_speed+.25);
  expect(errors).toEqual([]);
});
