import {test,expect} from '@playwright/test';
test('value controls commit on release, cancel safely and support keyboard semantics',async({page})=>{
  await page.setViewportSize({width:1280,height:720});
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto('http://127.0.0.1:4209/?test=1&backend=webgl2',{waitUntil:'domcontentloaded'});
  await page.waitForFunction(()=>window.__nir?.state().ready&&!window.__nir.state().loading);
  await page.keyboard.press('Enter');
  await page.waitForFunction(()=>window.__nir.state().dialogue&&!window.__nir.state().loading);
  await page.keyboard.press('Escape');
  await page.waitForFunction(()=>window.__nir.state().screen==='Menu'&&!window.__nir.state().loading);
  const slider=page.getByRole('slider',{name:'Volume',exact:true});
  await expect(slider).toBeAttached();
  expect(Number(await slider.getAttribute('aria-valuenow'))).toBeCloseTo(await page.evaluate(()=>window.__nir.state().preferences.bgm_volume),5);
  await slider.focus();await page.keyboard.press('Home');
  await expect(slider).toHaveAttribute('aria-valuenow','0');
  await expect(slider).toBeFocused();
  await page.keyboard.press('ArrowRight');
  await expect.poll(async()=>Number(await slider.getAttribute('aria-valuenow'))).toBeCloseTo(.1,5);
  const stale=JSON.parse(await slider.getAttribute('data-action'));
  await page.mouse.move(168,170);await page.mouse.down();
  await page.mouse.move(574,170);
  await expect.poll(()=>page.evaluate(()=>window.__nir.state().preferences.bgm_volume)).toBeCloseTo(.1,5);
  await page.mouse.up();
  await expect.poll(()=>page.evaluate(()=>window.__nir.state().preferences.bgm_volume)).toBeCloseTo(.8,5);
  await page.evaluate(a=>window.__nir.action(a),stale);
  await expect.poll(async()=>Number(await slider.getAttribute('aria-valuenow'))).toBeCloseTo(.8,5);
  await page.mouse.move(574,170);await page.mouse.down();await page.mouse.move(284,170);
  await page.locator('canvas').dispatchEvent('pointercancel');
  await page.mouse.up();
  await expect.poll(async()=>Number(await slider.getAttribute('aria-valuenow'))).toBeCloseTo(.8,5);
  const toggle=page.getByRole('switch',{name:'Motion',exact:true});
  await toggle.focus();await page.keyboard.press('Space');
  await expect(toggle).toHaveAttribute('aria-checked','true');
  expect(errors).toEqual([]);
});
