[package]
name = "nir-presentation"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
nir-format.workspace = true
cosmic-text.workspace = true
fluent-bundle.workspace = true
unic-langid.workspace = true
unicode-segmentation.workspace = true
unicode-script = "=0.5.8"
serde.workspace = true
