[package]
name = "nir-player"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
nir-format.workspace = true
nir-core.workspace = true
nir-content.workspace = true
nir-assets.workspace = true
nir-presentation.workspace = true
serde.workspace = true
serde_json.workspace = true
